# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sborrego <sborrego@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/28 22:30:35 by sborrego          #+#    #+#              #
#    Updated: 2023/08/29 14:03:53 by sborrego         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC=cc
CFLAGS= -Wall -Wextra -Werror

bsq: main.c init.c draw.c map.c bsq.c error.c
	$(CC) $(CFLAGS) -o bsq main.c init.c draw.c map.c bsq.c error.c
